---
name: CI / cd .

on:
  push:
    branches: [ master ]
  pull_request:
    paths:
      - 'docs/**'
      - 'templates/**'
      - 'cookbook/**'
      - '.github/workflows/_lint.yml'
      - '.github/workflows/doc_lint.yml'
  workflow_dispatch:

jobs:
  check:
    name: Check for "from langchain import x" imports
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run import check
      run: |
        # We should not encourage imports directly from main init file
        # Expect for hub
        git grep 'from langchain import' {docs/docs,templates,cookbook} | grep -vE 'from langchain import (hub)' && exit 1 || exit 0

  lint:
      name: "-"
      uses:
        ./.github/workflows/_lint.yml
      with:
        working-directory: "."
      secrets: inherit